### ISSUE TITLE
1.9 TODO

### ISSUE THREAD

**Issue by xfgryujk** [xfgryujk/blivechat#143]
* [x] 写wiki文档
* [x] 第三方库改用CDN引入，减少打包大小
* [x] 前端添加消息模型类，统一传参，防止以后加新的字段漏改
* [x] 样式生成器预览放到iframe，防止影响到外面网页
* [x] 添加`data/custom_public`目录，用来对前端暴露一些文件（图片、CSS、字体）
* [x] 添加`引入服务器预设CSS`选项，用于自动引入`custom_public`目录预设的CSS
* [x] 添加一些属性用于CSS选择器区分（加什么还没想好，暂定舰队等级、SC档位等）
* [x] 修复合并相似弹幕导致的可能卡住的问题
* [x] ~~预加载表情图片尺寸，防止加载前后布局发生变化，评论滚动不到底部~~ 解决了一部分，CSS设置的尺寸太大时还是有问题，完全解决性价比不高
* [x] 根据表情图片尺寸添加class，用于给大表情设置不同的尺寸
* [x] 添加插件接口
* [x] 完善插件发送的信息，比如勋章等级、购买舰长时长
* [x] 添加插件SDK
* [x] 添加消息日志插件
* [x] 添加TTS插件
* [x] 添加GUI插件
* [x] 添加管理插件的前端页面
* [x] 添加插件打包脚本
* [x] 添加插件文档
* [x] 开放平台请求加上限流的保险措施，防止被风控下架
* [x] 其他防雪崩措施，比如初始化房间、重连加上随机延迟
