### ISSUE TITLE
1.10 TODO

### ISSUE THREAD

**Issue by xfgryujk** [xfgryujk/blivechat#199]
* [x] 写注意事项和升级指南文档
* [x] 默认的Python版本升级到3.12，最低版本暂时不变（只影响Docker）
* [x] 接开放平台停止推送的消息
* [x] ？
* [x] SC固定栏支持滚动
* [x] ~~礼物消息用新的元素，支持显示礼物图标~~ 会破坏现有的样式，还是算了，有需要的话改自定义模板吧
* [x] 把原版YouTube样式放入`@layer`，这样自定义样式就不用加`!important`了
* [x] ~~样式生成器预览性能优化，用`adoptedStyleSheets`代替赋值`style`元素的`innerText`~~ 因为`adoptedStyleSheets.replace`不支持`@import`，所以改方案了
* [x] ~~样式生成器预览性能优化，分离`@import`的规则到另一个`style`元素，防止重复解析~~
* [x] 样式生成器预览性能优化，`innerText`改成`textContent`
* [x] 样式生成器界面优化，支持折叠
* [x] Gemini翻译改成OpenAI接口翻译
* [x] 前端可选择自定义模板（大概会做成房间页面里的iframe，通过postMessage发消息进去）
* [x] 添加前端模板SDK
* [x] 添加前端模板示例
* [x] 添加自定义模板文档

**Comment by SSSSSSSan** [comment]
目前python3.8.6运行正常，开发环境版本更新会影响更低版本的python运行么QwQ

**Comment by xfgryujk** [comment]
> 目前python3.8.6运行正常，开发环境版本更新会影响更低版本的python运行么QwQ

暂时不影响
